### ISSUE TITLE
"Unsupported item key" errors

### ISSUE THREAD

**Issue by danboid** [AceSlash/zabbix_zfs-on-linux#3]
Hi @AceSlash !

Thanks for writing and sharing this zabbix ZoL template, unfortunately it isn't working properly for me yet.

Before I get onto my actual problem, could you please update the description on https://share.zabbix.com/zfs-on-linux from:

"The documentation has moved to github: https://github.com/AceSlash/zabbix_zfs-on-linux" to something like:

"Please use the newer version of this template available from https://github.com/AceSlash/zabbix_zfs-on-linux"

I am running zabbix 4.0 under Ubuntu 18.04. The ZoL host I'm trying to monitor is proxmox VE / Debian 9. I removed the older version of your template and user parameters and replaced them with the updated ones from this repo, but after restarting the zabbix agent on my PVE server I see these errors in the zabbix-agent log:

```
18508:20190605:093052.533 Starting Zabbix Agent [demeter.cs.salford.ac.uk]. Zabbix 4.0.8 (revision 2b50c941de).
 18508:20190605:093052.534 **** Enabled features ****
 18508:20190605:093052.534 IPv6 support:          YES
 18508:20190605:093052.534 TLS support:           YES
 18508:20190605:093052.534 **************************
 18508:20190605:093052.534 using configuration file: /etc/zabbix/zabbix_agentd.conf
 18508:20190605:093052.534 agent #0 started [main process]
 18509:20190605:093052.535 agent #1 started [collector]
 18510:20190605:093052.535 agent #2 started [listener #1]
 18511:20190605:093052.536 agent #3 started [listener #2]
 18512:20190605:093052.536 agent #4 started [listener #3]
 18513:20190605:093052.537 agent #5 started [active checks #1]
 18513:20190605:093052.546 active check "zfs.arcstats[arc_dnode_limit]" is not supported: Unsupported item key.
 18513:20190605:093052.546 active check "zfs.arcstats[arc_meta_limit]" is not supported: Unsupported item key.
 18513:20190605:093052.546 active check "zfs.arcstats[arc_meta_used]" is not supported: Unsupported item key.
 18513:20190605:093052.546 active check "zfs.arcstats[bonus_size]" is not supported: Unsupported item key.
 18513:20190605:093052.546 active check "zfs.arcstats[c_max]" is not supported: Unsupported item key.
 18513:20190605:093052.546 active check "zfs.arcstats[c_min]" is not supported: Unsupported item key.
 18513:20190605:093052.546 active check "zfs.arcstats[data_size]" is not supported: Unsupported item key.
 18513:20190605:093052.546 active check "zfs.arcstats[dbuf_size]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[dnode_size]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[hdr_size]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[hits]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[metadata_size]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[mfu_hits]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[mfu_size]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[misses]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[mru_hits]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[mru_size]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.arcstats[size]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.fileset.discovery" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.get.param[zfs_arc_dnode_limit_percent]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.get.param[zfs_arc_meta_limit_percent]" is not supported: Unsupported item key.
 18513:20190605:093052.547 active check "zfs.pool.discovery" is not supported: Unsupported item key.
```

Thanks for your help!

**Comment by danboid** [comment]
Currently, the only bit of ZFS data I am getting under zabbix is the ZFS on Linux version.

**Comment by danboid** [comment]
I may be able to fix this by changing everything from active to passive checks but I'd like to know what the proper solution is.

**Comment by danboid** [comment]
I am using the ZoL_with_sudo.conf userparameters file, seeing as zpool and zfs are located under /sbin under PVE.

**Comment by danboid** [comment]
Oops!

I had copied the user parameters file into the sudoers.d dir by mistake. After copying it to the right place and restarting it looks like its working now.

**Comment by AceSlash** [comment]
hey @danboid ,

Just a quick note about the usage of sudo. On Ubuntu 18.04, you have ZoL version 0.7+, so you don't need sudo. The fact that the "zfs" and "zpool" binaries are in "/sbin" doesn't matter.

You should remove the sudo rights and directly use the ZoL_without_sudo.conf parameter file (don't forget to remove the other one).

**Comment by danboid** [comment]
Thanks for the tip but the ZoL host I'm monitoring is Debian 9.

**Comment by AceSlash** [comment]
Oh sorry I misread. If you can, I would install ZoL from the Debian backports to get ZoL 0.7.12, which is a lot better than the outdated 0.6.5 that is in the standard repository.

**Comment by danboid** [comment]
I'm pretty sure proxmox bundle their own kernel and ZFS packages, which are likely as up to date as backports. Best stick with theirs I think.

**Comment by AceSlash** [comment]
It may be a good idea to check the version shipped with proxmox then, they may well use the 0.7 branch ;)

**Comment by danboid** [comment]
It definitely is using 0.7, I'm not not sure of the micro version.
